apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: inventory
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: coolstore
    template:
      ref: inventory
