kind: Service
apiVersion: v1
metadata:
  name: catalog-spring-boot
  labels:
    app: catalog-spring-boot
    app.kubernetes.io/component: catalog-spring-boot
    app.kubernetes.io/instance: catalog-spring-boot
    app.kubernetes.io/name: catalog-spring-boot
    app.kubernetes.io/part-of: coolstore
    app.openshift.io/runtime: java
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  selector:
    app: catalog-spring-boot
    deployment: catalog-spring-boot

