apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coolstore
spec:
  destination:
    namespace: coolstore-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/blues-man/coolstore-gitops-manifests
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true

